### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kasium** [christopherpickering/pylint-per-file-ignores#101]
## System Info
- pylint==3.0.1
astroid==3.0.1
- pylint-per-file-ignores==1.3.2

## Issue
With pylint 3 it's no longer possible to disable the message of a plugin if multiple jobs are used

## How To Reproduce

**pyproject.toml**
```toml
[tool.pylint.main]
jobs = 2
load-plugins = ["pylint.extensions.private_import", "pylint_per_file_ignores"]

[tool.pylint."messages control"]
enable = ["all"]

[tool.pylint-per-file-ignores]
"tests/" = "import-private-name"
```

**project/\_\_init\_\_.py**
_empty_

**project/_main.py**
```py
X = 123
```

**tests/\_\_init\_\_.py**
_empty_

**tests/_main.py**
```py
from project import _main
print(_main.X)
```

Execute `pylint project/ tests/`

**Output**
```
************* Module project._main
project/_main.py:1:0: C0304: Final newline missing (missing-final-newline)
project/_main.py:1:0: C0114: Missing module docstring (missing-module-docstring)
************* Module tests.test_main
tests/test_main.py:3:0: C0304: Final newline missing (missing-final-newline)
tests/test_main.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/test_main.py:1:0: C2701: Imported private object (_main) (import-private-name)
```

The last line is not expected
